### ISSUE TITLE
Module outcomes order logic

### ISSUE THREAD

**Issue by ooker** [edesign-erasmus/en#11]
Mooduli väljundite järjekorraloogika.

Right now they are ordered: intro > frontend > design.
Can or should we change it intro > design > frontend which seems to be a bit more logical order, because it follows the design/development process?

**Comment by rrrrando** [comment]
I'd say the first one is better, because in front end we have design and development pretty much at the same time

**Comment by rrrrando** [comment]
Oh you mean change the order in the menu. Yeah i agree that design should be first
